### ISSUE TITLE
tmp or placeholder?

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-skeleton#7]
I chose `tmp` as it was short. But `placeholder` is more idiomatic.

``` hbs
{{skeleton-img src="image.png" tmpSrc="foo.png"}}

vs

{{skeleton-img src="image.png" placeholderSrc="foo.png"}}
```

**Comment by michaeldupuisjr** [comment]
I like `placeholderSrc` as it's more expressive.

`tmpSrc` also has this notion of time, which I think may be misleading if this library is used to trigger images more than simply load a second image once it is ready. Triggering the "final" image, rather than relying on load, is something we're already seeing with the integration of `ember-in-viewport` so getting away from names that suggest loading/temporality is probably a good thing. `initialSrc` and `finalSrc` may be even better.

**Comment by danmcclain** [comment]
Also, `placeholder-src` might be a better format. Initial might be less clear, I feel placeholder has more insight than initial

**Comment by bcardarella** [comment]
I'm in favor of `placeholderSrc` as well. However, it does feel long. I think I might create aliases for `placeholderSrc` and `errorSrc`: `pSrc` `eSrc` that can also be used.
